sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

services:
  - mongodb

before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
